# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["http://192.168.1.229:2999"]
          allowed_headers: ["authorization", "content-type", "x-custom-header"]

  opencensus:
    endpoint: 0.0.0.0:55678

  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_binary:
        endpoint: 0.0.0.0:6832
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268

  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  batch:

exporters:
  otlp:
    endpoint: "http://192.168.1.229:14317"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9464"

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp, opencensus, zipkin]
      processors: [batch]
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp, opencensus]
      processors: [batch]
      exporters: [otlp, prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

  extensions: [health_check, pprof, zpages]
