server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.229:3100/loki/api/v1/push

scrape_configs:
  - job_name: "application_logs_RNDSTG"
    static_configs:
      - targets:
          - 192.168.1.229
        labels:
          job: "Logs_RNDSTG"
          app: "ProgrecApps_RNDSTG"
          __path__: "/var/log/RNDSTG-ORACLE/application.log"

  - job_name: "application_logs_RNDQA"
    static_configs:
      - targets:
          - 192.168.1.229
        labels:
          job: "Logs_RNDQA"
          app: "ProgrecApps_RNDQA"
          __path__: "/var/log/RNDQA-ORACLE/application.log"

  - job_name: "application_logs_INNVOATION"
    static_configs:
      - targets:
          - 192.168.1.229
        labels:
          job: "Logs_INNOVATION"
          app: "ProgrecApps_INNOVATION"
          __path__: "/var/log/INNOVATION/application.log"

  - job_name: "application_logs_INNVOATION-5"
    static_configs:
      - targets:
          - 192.168.1.229
        labels:
          job: "Logs_INNOVATION-5"
          app: "ProgrecApps_INNOVATION-5"
          __path__: "/var/log/INNOVATION-5/application.log"
  #  - job_name: "system"
  #    static_configs:
  #      - targets:
  #          - 192.168.1.229
  #        labels:
  #          job: "varlogs"
  # __path__: "/var/log/host_229/*.log"
  #          __path__: "/var/log/host_229/{syslog,kern.log,daemon.log,other_logs}.log"

  - job_name: "journal"
    journal:
      path: "/var/log/host_229/journal" # Adjust if necessary
      labels:
        job: "systemd-journal"
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"
      - source_labels: ["__journal__hostname"]
        target_label: "host"

    pipeline_stages:
      - match:
          selector: '{job="varlogs"}'
          stages:
            - drop:
                expression: "/var/log/host_229/auth.log/"

  - job_name: "docker-logs"
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
            time: time
            attrs: attrs
      - regex:
          expression: ".*containers/(?P<container_id>[^/]+)/.*-json.log$"
      - match:
          selector: '{job="docker-logs"}'
          stages:
            - docker: {}
    static_configs:
      - targets:
          - 192.168.1.229
        labels:
          job: "docker-logs"
          host: "docker-host"
          __path__: "/var/lib/docker/containers/*/*.log"
